pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: ${CI_REPO}
      tags: "feat-${CI_COMMIT_BRANCH##feat/}"
    secrets: [docker_username, docker_password]
    when:
      event: push
      branch: feat/*
